name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./scripts

    container:
      image: jackpar/fusion:1.0.0

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: make executable
      run: chmod +x entrypoint.sh

    - name: build and test
      run: ./entrypoint.sh
