name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jackpar/fusion:latest 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: build
      run: mkdir build && cd build && cmake .. && make && cd ../tests && tester ./tester_config.json
